---
title: "Week-03-Notes"
author: "Andrew Nalundasan"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output: 
  html_document:
    toc: true
    toc_depth: 3
    toc_float: true
    number_sections: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Overview Video

+ Assignment Feedback: 

    + Expectations: 
        + Readable, critical thinking, defending my position
        + Don't return a Q&A type response
        + Make connections to readings
        + Specific action items and including "HOW" ("what" is useless without a "how")
    + Find a mentor
        + Tammy?
        + Chad?
        + Eric van Gestel / Sandra?
        
+ Week 3 details

    + Challenges of presenting data to stakeholders and communicating to leadership
    + Persuasion as a tool for good
    + Forecasting and ethics
    
+ Necessary art of persuasion: 

    + "Leading people to a problem shared solution" 
    + sell yourself to employer thru interviewing
    + Persuade using WIIFM
        + "what's in it for me"
    + Leaders touch a heart before asking for a hand
    + 4 steps of being persuasive
        + sharpen persuasiveness skills and negotiating
        
+ Ethics readings ("women in forecasting")

    + Falsifying company documents (expense reports, etc.) - violating company code of ethics
    + 1/20 terminations was female
    + "women calculate, men judge" 
    
    

# Forecasting

+ The "Forecasted number" is the most powerful number in a business

+ Provide insight into how a company should manage its workforce and assts
+ See trends with workforce and customers
+ Inform Wall Street of our performance
+ Stakeholders when forecasting: 

    + Customers
    + Employees
    + Investors
    + Suppliers
    + Communities
    + Governments
    
+ Roles: 

    1. Sandbaggers (Pessimists)
        + undercommit and overperform
        + still negatively impacts trust
    2. Pinocchios (Optimists)
        + Overcommit and underperform
        + Great story tellers and too big for their briches 
    3. Steady Eddie (Realists)
        + Don't tell you what they want you to hear
        + Straight shooters
        
+ closing ratio

    1. Identify closing ratio through historical data
        + 'sales closing ratio' = sales_transactions / customer_contacts
    2. Once you know your closing ratio, you know what volume of sales proposals you need to reach your goal
    
+ Sales (funnel) and Pipeline stages: 

    Stage 1 (Awareness): Prospecting 
    Stage 2 (Discovery): Qualifying Leads
    Stage 3 (Discovery): Initial Meeting
    Stage 4 (Discovery): Define Prospect Needs
    Stage 5 (Evaluation): Make an Offer
    Stage 6 (Intent): Negotiation / Finalize Proposal
    Stage 7 (Purchase): Closing The Deal
    Stage 8 (Loyalty): Deliver the Product
    
    
+ Case Study: Women Count - Perceptions of Forecasting in Sales

    + Women are more trustworthy than men

# How to lie with Statistics 

+ How metrics can be manipulated to paint a false story
+ Biased Sampling: Polling a non-representative group
+ Small sample sizes: Picking an adequate sample size
+ Poorly-chosen averages: averaging values across non-uniform populations. Not representative of the truth
+ Results falling within the standard error: Survey can only be as accurate as its standard error
+ Using graphs to create an impression: Graphing data creatively provides room for false insights
+ The semi-attached figure: correlating one thing as proof of another
+ Post-hoc fallacy: Incorrectly asserting that there is a direct correlation between two findings (more nefarious)


# Necessary Art of Persuasion (Conger)

+ It's not 'persuading' it's 'building a business case'!
+ "Leading people to a problem's shared solution" (Conger)
+ 4 steps of being more persuasive:
    
    1. Establish credibility
        + Through building expertise
        + Through building relationships
    2. Frame goals with common ground
        + Trying to make connections
        + WIIFM - What's In It For Me?
    3. Reinforce using vivid language and compelling evidence
        + Reference points help drive a point
        + Combine data with storytelling
    4. Connect emotionally
        + Know and read your audience, but be mindful to match emotions
        + Dry run with inner circle
        + "Leaders touch a heart before they ask for a hand" 
            + Must make connections/build relationships!

# Ethics

+ Money and greed drives stupid behaviors of humans
+ Business Ethics: agreed upon code of conduct in business
+ Law & ethics are not synonymous
+ Staying within the law is a *minimal standard*
+ 5 simple rules of business ethics:

    1. What would your Mother say? (What would Google or NY Times say about it)
    2. Tell the Truth - it's easier to remember
    3. It's not the crime - it's the cover-up
    4. Be nice and respect others (sexual harassment, discrimination)
    5. Don't be a whore (what's your price?)
    + You aren't that smart and you'll likely get caught

+ What you own in life: 

    1. Your choices
    2. Your attitude
    3. Your integrity
    
# Women Count: Perceptions of Forecasting in Sales (Wilson & Dingus)



# The necessary art of persuasion (Conger)

+ Effective persuasion is a learning and negotiating process for leading your colleagues to a *shared solution* to a problem

+ The Idea at Work: 

    1. Establish credibility
        + Expertise + Relationships <- Reputation of trust
        + Relationships
    2. Frame goals on common ground
        + When no shared advantages are apparent, adjust your position
    3. Vividly reinforce your position
        + Numerical data leads to compelling stories
    4. Connect emotionally
        + mirrors and labels
        
+ to *persuade* is to effectively answer a 'why' question
+ Effective persuasion becomes a negotiating and learning process through which a persuader leads colleagues to a problem's shared solution
    
    + involves moving people to a position they don't currently hold
    
+ old school persuasion <- logic, persistence, and personal enthusiasm to get other to buy a good idea
+ new school persuasion <- testing and revising ideas in concert with your colleagues' concerns and needs
+ people who are honest, steady, and reliable have the upper hand in persuasion
+ substitutes speaking on your behalf outweighs you talking about yourself
+ persuasion is the process of identifying shared benefits
+ at the heart of framing is a solid understanding of your audience
+ persuasion ultimately becomes a matter of presenting evidence.
+ numbers alone don't make an emotional impact

    + supplement numerical data with examples, stories, metaphors, and analogies to make positions come alive

+ listeners absorb information in proportion to its vividness
+ persuasion is not all convincing and selling. Persuasion is learning and negotiating

+ How to be shitty at persuasion:

    1. Attempt to make their case with an up-front, hard sell
    2. Resist compromise
        + I disagree - no deal is better than a bad deal
    3. Thinking the secret of persuasion lies in presenting great agruments
        + never agrue. Work with your counterpart to uncover information, revealing their black swans
        + miror > label > repeat
    4. Assume persuasion is a one-shot effort
        + persuasion is a process, not an event

        